version: '3'

services:
  esp32_access_control_api:
    build: 
      context: ./
      args:
        - DATABASE_USERNAME=$DATABASE_USERNAME
        - DATABASE_PASSWORD=$DATABASE_PASSWORD
        - DATABASE_JDBC_URL=$DATABASE_JDBC_URL
        - HUMIO_TOKEN=$HUMIO_TOKEN
    container_name: esp32_access_control_api
    ports:
      - "8080:8080"
    networks:
      - esp32-api-compose-network
    restart: on-failure

networks:
  esp32-api-compose-network:
    driver: bridge
