FROM openjdk:11

# Args Config
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG DATABASE_JDBC_URL

# Env Config
ENV DATABASE_USERNAME ${DATABASE_USERNAME}
ENV DATABASE_PASSWORD ${DATABASE_PASSWORD}
ENV DATABASE_JDBC_URL ${DATABASE_JDBC_URL}

COPY ./target/acesscontrol-0.0.1-SNAPSHOT.jar /app/acesscontrol-0.0.1-SNAPSHOT.jar

WORKDIR /app

ENTRYPOINT ["java", "-jar", "acesscontrol-0.0.1-SNAPSHOT.jar"]

EXPOSE 8080