name: Deployment Workflow
on:
  push:
    branches: [main]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_SECRET }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ~/apps/esp32-access-control-api
          git pull origin main
          ./mvnw clean package -Dmaven.test.skip
          VARIAVEL_TEST=test
          docker compose up --build -d
