name: Deployment Workflow
on:
  workflow_dispatch:

  push:
    branches: [main]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing ssh connection
      uses: fifsky/ssh-action@master
      # uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_SECRET }}
        port: ${{ secrets.SERVER_PORT }}
        pass: ${{ secrets.SSH_PASSWORD }}
        script: |
          export DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}}
          export DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}
          export DATABASE_JDBC_URL=${{secrets.DATABASE_JDBC_URL}}
          cd ~/apps/esp32-access-control-api && ./deploy.sh
