name: Deployment Workflow
on:
  push:
    branches: [main]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_SECRET }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          ls -la
          pwd
